language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hyper-angular' ]; then cd .. && eval "mv $currentfolder generator-hyper-angular" && cd generator-hyper-angular; fi

